namespace SfUi.Core;

// 英語（既定言語）の文字列辞書。
public static partial class UiText
{
    private static Dictionary<string, string> BuildEn() => new(StringComparer.Ordinal)
    {
        // ---- 共通 ----
        ["Common_Ready"] = "Ready",
        ["Common_Cancel"] = "Cancel",
        ["Common_Canceled"] = "Canceled",
        ["Common_Running"] = "Running…",
        ["Common_FailedFmt"] = "Failed: {0}",
        ["Common_AddFavorite"] = "Add to favorites",
        ["Common_HistoryLabel"] = "History:",
        ["Common_RefreshTip"] = "Reload history",
        ["Common_SavedFmt"] = "Saved: {0}",
        ["Common_SaveFailedFmt"] = "Save failed: {0}",
        ["Common_CharsFmt"] = "({0:N0} chars)",
        ["Common_FavoriteAddedFmt"] = "Added to favorites: {0}",
        ["Common_ComponentsFmt"] = "{0} components",
        ["Common_ComponentsOfFmt"] = "{0}/{1} components",
        ["Common_UnexpectedErrorFmt"] = "An unexpected error occurred:{0}{1}",
        ["Common_ExitCodeFmt"] = "Exit code: {0} / {1:F0} ms",
        ["Common_TimeoutSuffix"] = " (timed out)",
        ["Common_NotFound"] = "(not found)",
        ["Common_All"] = "All",

        // ---- アプリ / MainWindow ----
        ["App_Title"] = "SfUi — Salesforce CLI Launcher",
        ["Main_DataPathFmt"] = "Data: {0}",
        ["Main_StatusDetailFmt"] = "Org: {0} / Folder: {1}",
        ["Main_NotSelected"] = "(not selected)",
        ["Main_DefaultFolder"] = "(default)",
        ["Main_OrgLabel"] = "Org:",
        ["Main_OrgTooltip"] = "Authenticated orgs (used for --target-org)",
        ["Main_RefreshOrgsTip"] = "Reload org list",
        ["Main_FolderLabel"] = "SF folder:",
        ["Main_FolderTooltip"] = "Working folder for sf commands (choose from recent or type)",
        ["Main_Browse"] = "Browse…",
        ["Main_Terminal"] = "Terminal",
        ["Main_TerminalTip"] = "Click: open a terminal in the current folder / Right-click: choose type",
        ["Main_TermWt"] = "Windows Terminal (default)",
        ["Main_TermPs"] = "PowerShell",
        ["Main_TermCmd"] = "Command Prompt",
        ["Main_TermWsl"] = "WSL",
        ["Main_Explorer"] = "Explorer",
        ["Main_ExplorerTip"] = "Click: open the current folder / Right-click: options",
        ["Main_OpenFolder"] = "Open this folder (default)",
        ["Main_CopyPath"] = "Copy folder path",
        ["Main_VsCode"] = "VS Code",
        ["Main_VsCodeTip"] = "Click: open the current folder in a new window / Right-click: options",
        ["Main_VsCodeNew"] = "Open in new window (default)",
        ["Main_VsCodeReuse"] = "Open in current window",
        ["Main_Browser"] = "Browser",
        ["Main_BrowserTip"] = "Click: open the org home / Right-click: choose URL",
        ["Main_BrowserHome"] = "Org home (default)",
        ["Main_BrowserSetup"] = "Org setup",
        ["Main_BrowserLogin"] = "Salesforce login",
        ["Main_BrowserInput"] = "Enter URL…",
        ["Main_BrowserRecent"] = "Recent URLs",
        ["Main_QuickToggle"] = "Quick",
        ["Main_QuickToggleTip"] = "Show/hide the favorites panel (Ctrl+1..9 to run)",
        ["Main_LanguageTip"] = "UI language",
        ["Tab_Soql"] = "SOQL",
        ["Tab_Apex"] = "Apex",
        ["Tab_Log"] = "Debug Logs",
        ["Tab_History"] = "History",
        ["Tab_Deploy"] = "Deploy",
        ["Tab_Command"] = "Command",
        ["Tab_Api"] = "REST API",
        ["Tab_Settings"] = "Settings",

        // ---- MainViewModel メッセージ ----
        ["Msg_SelectOrg"] = "Select an org in the top bar",
        ["Msg_LoadingOrgs"] = "Loading orgs…",
        ["Msg_OrgCountFmt"] = "Loaded {0} org(s)",
        ["Msg_OrgLoadFailedFmt"] = "Failed to load orgs: {0}",
        ["Msg_ReplaySoql"] = "Re-running SOQL from history",
        ["Msg_ReplayApex"] = "Apex loaded from history (press Ctrl+Enter to run)",
        ["Msg_ReplayCommand"] = "Command loaded from history (click Run to execute)",
        ["Msg_ReplayApi"] = "REST request loaded from history (click Send to execute)",
        ["Msg_ReplayDeploy"] = "Deploy settings loaded from history (click Run to execute)",
        ["Msg_ReplayUnsupportedFmt"] = "'{0}' cannot be re-run from history",
        ["Msg_FavoriteRunFmt"] = "Running favorite: {0}",
        ["Msg_FavoriteLoadedApexFmt"] = "Favorite loaded (Ctrl+Enter to run): {0}",
        ["Msg_FavoriteLoadedCommandFmt"] = "Favorite loaded (click Run to execute): {0}",
        ["Msg_FavoriteLoadedApiFmt"] = "Favorite loaded (click Send to execute): {0}",
        ["Msg_FavoriteLoadedDeployFmt"] = "Favorite loaded (click Run to execute): {0}",
        ["Msg_FavoriteUnsupportedFmt"] = "Favorites of type '{0}' are not supported",
        ["Msg_QuickSlotEmptyFmt"] = "No favorite is assigned to slot {0}",
        ["Msg_NoHistory"] = "No history to re-run",
        ["Msg_LanguageFmt"] = "Language: {0}",
        ["Msg_FolderNotExistFmt"] = "Folder does not exist: {0}",
        ["Msg_FolderSetFmt"] = "SF folder: {0}",
        ["Msg_TerminalFmt"] = "Terminal: {0}",
        ["Msg_ExplorerFmt"] = "Explorer: {0}",
        ["Msg_VsCodeFmt"] = "VS Code: {0}",
        ["Msg_Copied"] = "Folder path copied",
        ["Msg_CopyFailedFmt"] = "Copy failed: {0}",
        ["Msg_BrowserFmt"] = "Browser: {0}",
        ["Msg_BrowserFailedFmt"] = "Failed to open browser: {0}",
        ["Msg_GetOrgUrl"] = "Getting org URL…",
        ["Msg_NoInstanceUrl"] = "Could not get the org instanceUrl",
        ["Msg_InputUrlTitle"] = "Enter URL",
        ["Msg_InputUrlPrompt"] = "Enter the URL to open (e.g. https://myorg.my.salesforce.com/lightning/o/Account/list)",
        ["Dlg_BrowseFolderTitle"] = "Select sf working folder",

        // ---- SOQL ----
        ["Soql_Run"] = "▶ Run (Ctrl+Enter)",
        ["Soql_PreferRest"] = "Prefer REST",
        ["Soql_PreferRestTip"] = "Run via REST API (access token); falls back to sf data query on failure",
        ["Soql_ToolingApi"] = "Tooling API",
        ["Soql_HistoryTip"] = "Load a recently executed SOQL",
        ["Soql_ExportCsv"] = "Export CSV",
        ["Soql_CopyResults"] = "Copy results",
        ["Soql_EnterQuery"] = "Enter a SOQL query",
        ["Soql_ResultFmt"] = "{0} / {1} rows / {2:F0} ms",
        ["Soql_NoResultsToExport"] = "No results to export",
        ["Soql_CsvSaveTitle"] = "Save SOQL results as CSV",
        ["Soql_CsvFilter"] = "CSV files (*.csv)|*.csv|All files (*.*)|*.*",
        ["Soql_CsvSavedFmt"] = "CSV saved: {0}",
        ["Soql_CsvFailedFmt"] = "CSV export failed: {0}",
        ["Soql_NoResultsToCopy"] = "No results to copy",
        ["Soql_Copied"] = "Results copied to clipboard (TSV)",
        ["Soql_NoQueryFavorite"] = "No SOQL to add to favorites",

        // ---- 匿名Apex ----
        ["Apex_Run"] = "▶ Run (Ctrl+Enter)",
        ["Apex_LoadFile"] = "Open…",
        ["Apex_SaveFile"] = "Save…",
        ["Apex_HistoryTip"] = "Load a recently executed Apex script",
        ["Apex_FetchLatestLog"] = "Show latest log",
        ["Apex_FetchLatestLogTip"] = "Fetch the latest debug log stored in the org",
        ["Apex_LogsTip"] = "Debug log (sf apex run output / log fetched from the org)",
        ["Apex_EnterCode"] = "Enter Apex code",
        ["Apex_CompileError"] = "Compile error",
        ["Apex_CompileErrorFmt"] = "Compile error: {0}",
        ["Apex_RuntimeException"] = "Runtime exception",
        ["Apex_ExceptionFmt"] = "Exception (line {0}, column {1}): {2}{3}",
        ["Apex_SuccessFmt"] = "Success / {0:F0} ms",
        ["Apex_SuccessWithLogs"] = "Executed successfully (showing debug log)",
        ["Apex_Success"] = "Executed successfully",
        ["Apex_ErrorUnknown"] = "(unknown)",
        ["Apex_NoOrgLogs"] = "No debug log stored in the org (create one via Setup > Debug Logs or sf apex tail log)",
        ["Apex_OpenTitle"] = "Open Apex file",
        ["Apex_OpenFilter"] = "Apex files (*.apex)|*.apex|Text (*.txt)|*.txt|All files (*.*)|*.*",
        ["Apex_LoadedFmt"] = "Loaded: {0}",
        ["Apex_LoadFailedFmt"] = "Load failed: {0}",
        ["Apex_NoCodeToSave"] = "No code to save",
        ["Apex_SaveTitle"] = "Save Apex script",
        ["Apex_SaveFilter"] = "Apex files (*.apex)|*.apex|All files (*.*)|*.*",
        ["Apex_NoCodeFavorite"] = "No Apex code to add to favorites",
        ["Apex_LatestLogFmt"] = "Fetched latest log ({0:N0} chars)",
        ["Apex_LatestLogFailedFmt"] = "Failed to fetch log: {0}",

        // ---- デバッグログ ----
        ["Log_Refresh"] = "⟳ Refresh",
        ["Log_Fetch"] = "Fetch",
        ["Log_FetchTip"] = "Show the selected log content (or double-click)",
        ["Log_Save"] = "Save…",
        ["Log_Initial"] = "Click '⟳ Refresh' to load the log list",
        ["Log_ColStart"] = "Start time",
        ["Log_ColOperation"] = "Operation",
        ["Log_ColStatus"] = "Status",
        ["Log_ColDuration"] = "Time (ms)",
        ["Log_ColSize"] = "Size",
        ["Log_LoadingList"] = "Loading logs…",
        ["Log_CountFmt"] = "{0} log(s)",
        ["Log_ListFailedFmt"] = "Failed to load logs: {0}",
        ["Log_SelectToFetch"] = "Select a log to fetch",
        ["Log_FetchingFmt"] = "Fetching log {0}…",
        ["Log_Unavailable"] = "(content not available)",
        ["Log_FetchedFmt"] = "Done ({0:N0} chars)",
        ["Log_FetchFailedFmt"] = "Failed to fetch log: {0}",
        ["Log_NoLogToSave"] = "No log to save",
        ["Log_SaveTitle"] = "Save debug log",
        ["Log_SaveFilter"] = "Log files (*.log)|*.log|Text (*.txt)|*.txt|All files (*.*)|*.*",

        // ---- 履歴 ----
        ["History_TypeLabel"] = "Type:",
        ["History_SearchLabel"] = "Search:",
        ["History_SearchTip"] = "Search summary / params / org / folder",
        ["History_Refresh"] = "⟳ Refresh",
        ["History_CopyParams"] = "Copy params",
        ["History_CopyParamsTip"] = "Copy the SOQL / Apex / command body of the selected entry",
        ["History_DeleteSelected"] = "Delete selected",
        ["History_ClearAll"] = "Delete all",
        ["History_ColTime"] = "Time",
        ["History_ColType"] = "Type",
        ["History_ColOrg"] = "Org",
        ["History_ColFolder"] = "Folder",
        ["History_ColSummary"] = "Summary",
        ["History_ColStatus"] = "Status",
        ["History_ColDuration"] = "Duration (ms)",
        ["History_Empty"] = "No history yet. SOQL / Apex / command executions are recorded automatically.",
        ["History_DeleteConfirmFmt"] = "Delete this entry?{0}{1} [{2}] {3}",
        ["History_ClearConfirm"] = "Delete all history? (Result files are also removed)",
        ["Type_Soql"] = "SOQL",
        ["Type_Apex"] = "Apex",
        ["Type_Command"] = "Command",
        ["Type_Api"] = "API",
        ["Type_Deploy"] = "Deploy",
        ["Type_Org"] = "Org",
        ["Status_Success"] = "Success",
        ["Status_Error"] = "Error",
        ["Status_Canceled"] = "Canceled",

        // ---- コマンド ----
        ["Command_Run"] = "▶ Run (Enter)",
        ["Command_InputTip"] = "Arguments for sf (e.g. org list / data query --query ...). A leading 'sf' is allowed.",
        ["Command_StdOutTab"] = "stdout",
        ["Command_StdErrTab"] = "stderr",
        ["Command_Enter"] = "Enter a command",
        ["Command_EnterArgs"] = "Enter sf arguments (e.g. org list)",
        ["Command_HistoryTip"] = "Load a recently executed command",
        ["Command_DangerConfirmFmt"] = "This operation includes '{0}'. Run it?{1}{1}sf {2}",
        ["Command_NoCommandFavorite"] = "No command to add to favorites",

        // ---- REST API ----
        ["Api_Send"] = "Send",
        ["Api_PathTip"] = "Path from instanceUrl (e.g. /services/data/v67.0/limits)",
        ["Api_HistoryTip"] = "Load a recently sent request",
        ["Api_BodyLabel"] = "Request body (JSON, used for POST/PATCH)",
        ["Api_ResponseTip"] = "Response (JSON is pretty-printed)",
        ["Api_EnterPath"] = "Enter a path (e.g. /services/data/v67.0/limits)",
        ["Api_SendConfirmFmt"] = "Send a {0} request?{1}{1}{0} {2}",
        ["Api_Sending"] = "Sending…",
        ["Api_NoPathFavorite"] = "No path to add to favorites",

        // ---- デプロイ ----
        ["Deploy_Operation"] = "Operation:",
        ["Deploy_SourcePath"] = "Source:",
        ["Deploy_SourceTip"] = "Source to deploy (e.g. force-app). Empty = deploy tracked changes",
        ["Deploy_Manifest"] = "Manifest:",
        ["Deploy_ManifestTip"] = "Path to package.xml (optional)",
        ["Deploy_TestLevel"] = "Test level:",
        ["Deploy_Tests"] = "Tests:",
        ["Deploy_TestsTip"] = "Apex test names for RunSpecifiedTests (comma-separated)",
        ["Deploy_JobIdTip"] = "Job ID for report / quick deploy (empty = --use-most-recent)",
        ["Deploy_UseMostRecent"] = "Use most recent",
        ["Deploy_UseMostRecentTip"] = "--use-most-recent (use the latest validate/deploy)",
        ["Deploy_HistoryTip"] = "Load a recent deploy operation",
        ["Deploy_PreviewTip"] = "Command to be executed (copyable)",
        ["Deploy_OutputTip"] = "sf output (JSON is pretty-printed)",
        ["Deploy_ConfirmFmt"] = "Run this deploy operation?{0}{0}{1}",
        ["Deploy_Running"] = "Running… output appears when finished (click Cancel to abort)",
        ["Deploy_ExitFmt"] = "Exit code: {0} / {1:F1} min",
        ["Deploy_BrowseSourceTitle"] = "Select source directory",
        ["Deploy_BrowseManifestTitle"] = "Select package.xml (manifest)",
        ["Deploy_ManifestFilter"] = "Manifest (*.xml)|*.xml|All files (*.*)|*.*",
        ["Op_Deploy"] = "Deploy (start)",
        ["Op_Validate"] = "Validate (validate)",
        ["Op_Quick"] = "Quick deploy (quick)",
        ["Op_Report"] = "Report (report)",
        ["Op_Retrieve"] = "Retrieve metadata (retrieve)",

        // ---- クイックパネル ----
        ["Quick_Title"] = "Quick Panel (Ctrl+1..9)",
        ["Quick_TitleTip"] = "Favorites in registration order. Press Ctrl+<number> to run instantly.",
        ["Quick_Hint"] = "Double-click / Ctrl+<number> to run, right-click to remove",
        ["Quick_Run"] = "Run",
        ["Quick_Remove"] = "Remove from favorites",
        ["Quick_ConfirmRemoveFmt"] = "Remove from favorites?{0}[{1}] {2}",
        ["Quick_TypeUrl"] = "URL",
        ["Quick_TypeFolder"] = "Folder",

        // ---- 設定 ----
        ["Settings_Title"] = "Settings",
        ["Settings_DataRootFmt"] = "Data folder: {0}",
        ["Settings_OpenDataFolder"] = "Open data folder",
        ["Settings_Reload"] = "Reload",
        ["Settings_ReloadTip"] = "Reload the form with the current file values",
        ["Settings_SfGroup"] = "Salesforce CLI",
        ["Settings_SfPath"] = "sf path:",
        ["Settings_SfPathTip"] = "Full path to sf.cmd. Empty = auto-detect (SFUI_SF_PATH → Program Files → PATH)",
        ["Settings_Browse"] = "Browse…",
        ["Settings_Clear"] = "Clear",
        ["Settings_ClearTip"] = "Clear the override and use auto-detection",
        ["Settings_ToolsGroup"] = "Tools",
        ["Settings_Terminal"] = "Terminal:",
        ["Settings_TerminalTip"] = "Full path to Windows Terminal (wt.exe). Empty = auto-detect",
        ["Settings_VsCode"] = "VS Code:",
        ["Settings_VsCodeTip"] = "Full path to code.cmd. Empty = auto-detect",
        ["Settings_HistoryGroup"] = "History & Results",
        ["Settings_HistoryLimit"] = "History limit:",
        ["Settings_PerType"] = "per type",
        ["Settings_Threshold"] = "Result threshold:",
        ["Settings_ThresholdSuffix"] = "KB — larger results are stored separately under results/",
        ["Settings_SeedSamples"] = "Seed sample history (SOQL / Apex / Command / REST)",
        ["Settings_SeedSamplesTip"] = "Add commonly used templates to history (duplicates are skipped)",
        ["Settings_ConfirmGroup"] = "Confirmation",
        ["Settings_ConfirmPolicy"] = "Confirm policy:",
        ["Settings_Save"] = "Save",
        ["Settings_Loaded"] = "Loaded the current settings",
        ["Settings_DetectedFmt"] = "Auto-detected: sf={0} / wt={1} / code={2}",
        ["Settings_BrowseSfTitle"] = "Select the sf executable (sf.cmd)",
        ["Settings_SfFilter"] = "sf command (*.cmd;*.exe;*.bat)|*.cmd;*.exe;*.bat|All files (*.*)|*.*",
        ["Settings_BrowseTerminalTitle"] = "Select Windows Terminal (wt.exe)",
        ["Settings_ExeFilter"] = "Executable (*.exe)|*.exe|All files (*.*)|*.*",
        ["Settings_BrowseVsCodeTitle"] = "Select VS Code CLI (code.cmd)",
        ["Settings_CodeFilter"] = "code (*.cmd;*.exe;*.bat)|*.cmd;*.exe;*.bat|All files (*.*)|*.*",
        ["Settings_SeedConfirmFmt"] = "Add representative samples (SOQL / Apex / Command / REST API) to history?{0}Duplicates are skipped.",
        ["Settings_SeedDoneFmt"] = "Sample history: {0} added / {1} skipped",
        ["Settings_InvalidHistoryLimit"] = "History limit must be an integer >= 1",
        ["Settings_InvalidThreshold"] = "Result threshold must be an integer >= 0 (KB)",
        ["Settings_SavedSfMissing"] = "Saved (sf not found — check the path)",
        ["Settings_SavedSfFmt"] = "Saved / sf: {0}",
        ["Policy_Dangerous"] = "Dangerous only",
        ["Policy_Always"] = "Always",
        ["Policy_Never"] = "Never",

        // ---- Core（エラーメッセージ等）----
        ["Core_OrgSelectRequired"] = "No target org specified.",
        ["Core_SoqlRequired"] = "No SOQL provided.",
        ["Core_OrgListFailedFmt"] = "Failed to load orgs: {0}",
        ["Core_TokenFailedFmt"] = "Failed to get the access token ({0}): {1}",
        ["Core_ApexRunFailed"] = "Execution failed.",
        ["Core_LogListFailedFmt"] = "Failed to list logs: {0}",
        ["Core_LogFetchFailedFmt"] = "Failed to fetch the log: {0}",
        ["Core_InstanceUrlMissing"] = "Could not get the org instanceUrl.",
        ["Core_SfNotFound"] = "sf command not found. Install Salesforce CLI or set SFUI_SF_PATH to sf.cmd.",
        ["Core_SfStartFailedFmt"] = "Failed to start the sf command: {0}",
        ["Core_Timeout"] = "The command timed out.",
        ["Core_FailedExitCodeFmt"] = "The command failed (ExitCode={0}).",
        ["Core_SoqlFailedFmt"] = "SOQL execution failed: {0}",
        ["Launch_PsFmt"] = "PowerShell started: {0}",
        ["Launch_CmdFmt"] = "Command Prompt started: {0}",
        ["Launch_WslFmt"] = "WSL started: {0}",
        ["Launch_WtFmt"] = "Windows Terminal started: {0}",
        ["Launch_CmdFallbackFmt"] = "Command Prompt started (Windows Terminal not found): {0}",
        ["Launch_TerminalFailedFmt"] = "Failed to start the terminal: {0}",
        ["Launch_ExplorerFmt"] = "Explorer: {0}",
        ["Launch_ExplorerFailedFmt"] = "Failed to start Explorer: {0}",
        ["Launch_VsCodeNotFound"] = "VS Code (code.cmd) was not found.",
        ["Launch_VsCodeFmt"] = "VS Code started: {0}",
        ["Launch_VsCodeFailedFmt"] = "Failed to start VS Code: {0}",
        ["Launch_BrowserFmt"] = "Browser: {0}",
        ["Launch_BrowserFailedFmt"] = "Failed to open the browser: {0}",

        // ---- サンプル履歴（要約）----
        ["Sample_Soql_Basic"] = "Accounts — basic list (10)",
        ["Sample_Soql_Industry"] = "Accounts with industry & revenue (latest 20)",
        ["Sample_Soql_Count"] = "Number of accounts",
        ["Sample_Soql_Recent"] = "Accounts created in the last 7 days",
        ["Sample_Soql_Contacts"] = "Contacts with email (latest 20)",
        ["Sample_Soql_Rel"] = "Contacts with account name (relationship)",
        ["Sample_Soql_Opps"] = "Open opportunities (by close date, 50)",
        ["Sample_Soql_Tasks"] = "Open tasks (by due date, 50)",
        ["Sample_Soql_Users"] = "Active users (50)",
        ["Sample_Apex_UserInfo"] = "Show user and org information",
        ["Sample_Apex_Query"] = "Query 5 accounts and debug them",
        ["Sample_Apex_Savepoint"] = "Rollback with a savepoint (safe DML sample)",
        ["Sample_Apex_Limits"] = "Check governor limits",
        ["Sample_Apex_DmlCatch"] = "DmlException handling example",
        ["Sample_Apex_Json"] = "Serialize a Map to JSON",
        ["Sample_Command_OrgList"] = "List authenticated orgs",
        ["Sample_Command_OrgDisplay"] = "Show the selected org (URL / API version)",
        ["Sample_Command_OrgOpen"] = "Open org home in the browser",
        ["Sample_Command_DataQuery"] = "SOQL via CLI (REST fallback check)",
        ["Sample_Command_LogList"] = "List recent debug logs",
        ["Sample_Command_LogGet"] = "Fetch the latest debug log",
        ["Sample_Command_DeployReport"] = "Review the last deploy result",
        ["Sample_Command_AliasList"] = "List org aliases",
        ["Sample_Api_Limits"] = "API usage (limits)",
        ["Sample_Api_Sobjects"] = "Object list (metadata)",
        ["Sample_Api_Describe"] = "Account field definitions",
        ["Sample_Api_Query"] = "SOQL via REST (5 accounts)",
        ["Sample_Api_Tooling"] = "Tooling API: Apex classes (10)",
        ["Sample_Api_Recent"] = "Recently viewed records",
        ["Sample_Api_Count"] = "Account count (COUNT query)",
    };
}
