namespace SfUi.Core;

// 日本語の文字列辞書（キーは英語辞書と同一）。
public static partial class UiText
{
    private static Dictionary<string, string> BuildJa() => new(StringComparer.Ordinal)
    {
        // ---- 共通 ----
        ["Common_Ready"] = "準備完了",
        ["Common_Cancel"] = "キャンセル",
        ["Common_Canceled"] = "キャンセルしました",
        ["Common_Running"] = "実行中…",
        ["Common_FailedFmt"] = "失敗: {0}",
        ["Common_AddFavorite"] = "お気に入り追加",
        ["Common_HistoryLabel"] = "履歴:",
        ["Common_RefreshTip"] = "履歴を再読込",
        ["Common_SavedFmt"] = "保存: {0}",
        ["Common_SaveFailedFmt"] = "保存に失敗: {0}",
        ["Common_CharsFmt"] = "（{0:N0} 文字）",
        ["Common_FavoriteAddedFmt"] = "お気に入りに追加: {0}",
        ["Common_ComponentsFmt"] = "{0} コンポーネント",
        ["Common_ComponentsOfFmt"] = "{0}/{1} コンポーネント",
        ["Common_UnexpectedErrorFmt"] = "予期しないエラーが発生しました:{0}{1}",
        ["Common_ExitCodeFmt"] = "終了コード: {0} / {1:F0} ms",
        ["Common_TimeoutSuffix"] = "（タイムアウト）",
        ["Common_NotFound"] = "未検出",
        ["Common_All"] = "すべて",

        // ---- アプリ / MainWindow ----
        ["App_Title"] = "SfUi — Salesforce CLI ランチャー",
        ["Main_DataPathFmt"] = "データ: {0}",
        ["Main_StatusDetailFmt"] = "組織: {0} ／ フォルダ: {1}",
        ["Main_NotSelected"] = "未選択",
        ["Main_DefaultFolder"] = "（既定）",
        ["Main_OrgLabel"] = "組織:",
        ["Main_OrgTooltip"] = "認証済み組織（コマンドの --target-org に使用）",
        ["Main_RefreshOrgsTip"] = "組織一覧を更新",
        ["Main_FolderLabel"] = "SFフォルダ:",
        ["Main_FolderTooltip"] = "sf コマンドを実行するフォルダ（最近使用したフォルダから選択 or 入力）",
        ["Main_Browse"] = "参照…",
        ["Main_Terminal"] = "ターミナル",
        ["Main_TerminalTip"] = "クリック: 現在のフォルダでターミナルを開く / 右クリック: 種類を選択",
        ["Main_TermWt"] = "Windows Terminal（既定）",
        ["Main_TermPs"] = "PowerShell",
        ["Main_TermCmd"] = "コマンド プロンプト",
        ["Main_TermWsl"] = "WSL",
        ["Main_Explorer"] = "エクスプローラー",
        ["Main_ExplorerTip"] = "クリック: 現在のフォルダを開く / 右クリック: オプション",
        ["Main_OpenFolder"] = "このフォルダを開く（既定）",
        ["Main_CopyPath"] = "フォルダパスをコピー",
        ["Main_VsCode"] = "VS Code",
        ["Main_VsCodeTip"] = "クリック: 現在のフォルダを新規ウィンドウで開く / 右クリック: オプション",
        ["Main_VsCodeNew"] = "新規ウィンドウで開く（既定）",
        ["Main_VsCodeReuse"] = "現在のウィンドウで開く",
        ["Main_Browser"] = "ブラウザ",
        ["Main_BrowserTip"] = "クリック: 現在の組織のホームを開く / 右クリック: URL を選択",
        ["Main_BrowserHome"] = "組織ホーム（既定）",
        ["Main_BrowserSetup"] = "組織の設定（Setup）",
        ["Main_BrowserLogin"] = "Salesforce ログイン",
        ["Main_BrowserInput"] = "URL を入力…",
        ["Main_BrowserRecent"] = "最近の URL",
        ["Main_QuickToggle"] = "クイック",
        ["Main_QuickToggleTip"] = "お気に入りパネルの表示/非表示（Ctrl+1..9 で実行）",
        ["Main_LanguageTip"] = "UI の言語",
        ["Tab_Soql"] = "SOQL",
        ["Tab_Apex"] = "匿名Apex",
        ["Tab_Log"] = "デバッグログ",
        ["Tab_History"] = "履歴",
        ["Tab_Deploy"] = "デプロイ",
        ["Tab_Command"] = "コマンド",
        ["Tab_Api"] = "REST API",
        ["Tab_Settings"] = "設定",

        // ---- MainViewModel メッセージ ----
        ["Msg_SelectOrg"] = "上部バーで組織を選択してください",
        ["Msg_LoadingOrgs"] = "組織一覧を取得中…",
        ["Msg_OrgCountFmt"] = "組織 {0} 件を取得しました",
        ["Msg_OrgLoadFailedFmt"] = "組織一覧の取得に失敗: {0}",
        ["Msg_ReplaySoql"] = "履歴から SOQL を再実行します",
        ["Msg_ReplayApex"] = "履歴から匿名Apex を読み込みました（Ctrl+Enter で実行）",
        ["Msg_ReplayCommand"] = "履歴からコマンドを読み込みました（実行ボタンで再実行）",
        ["Msg_ReplayApi"] = "履歴から REST リクエストを読み込みました（送信ボタンで再実行）",
        ["Msg_ReplayDeploy"] = "履歴からデプロイ設定を読み込みました（実行ボタンで再実行）",
        ["Msg_ReplayUnsupportedFmt"] = "「{0}」の再実行には対応していません",
        ["Msg_FavoriteRunFmt"] = "お気に入りを実行: {0}",
        ["Msg_FavoriteLoadedApexFmt"] = "お気に入りを読み込みました（Ctrl+Enter で実行）: {0}",
        ["Msg_FavoriteLoadedCommandFmt"] = "お気に入りを読み込みました（実行ボタンで再実行）: {0}",
        ["Msg_FavoriteLoadedApiFmt"] = "お気に入りを読み込みました（送信ボタンで再実行）: {0}",
        ["Msg_FavoriteLoadedDeployFmt"] = "お気に入りを読み込みました（実行ボタンで再実行）: {0}",
        ["Msg_FavoriteUnsupportedFmt"] = "「{0}」のお気に入りには対応していません",
        ["Msg_QuickSlotEmptyFmt"] = "お気に入り {0} は未登録です",
        ["Msg_NoHistory"] = "再実行できる履歴がありません",
        ["Msg_LanguageFmt"] = "言語: {0}",
        ["Msg_FolderNotExistFmt"] = "フォルダが存在しません: {0}",
        ["Msg_FolderSetFmt"] = "SFフォルダ: {0}",
        ["Msg_TerminalFmt"] = "ターミナル: {0}",
        ["Msg_ExplorerFmt"] = "エクスプローラー: {0}",
        ["Msg_VsCodeFmt"] = "VS Code: {0}",
        ["Msg_Copied"] = "フォルダパスをコピーしました",
        ["Msg_CopyFailedFmt"] = "コピーに失敗: {0}",
        ["Msg_BrowserFmt"] = "ブラウザ: {0}",
        ["Msg_BrowserFailedFmt"] = "ブラウザ起動に失敗: {0}",
        ["Msg_GetOrgUrl"] = "組織の URL を取得中…",
        ["Msg_NoInstanceUrl"] = "組織の instanceUrl を取得できませんでした",
        ["Msg_InputUrlTitle"] = "URL を入力",
        ["Msg_InputUrlPrompt"] = "開く URL を入力してください（例: https://hks3.my.salesforce.com/lightning/o/Account/list）",
        ["Dlg_BrowseFolderTitle"] = "SF 実行フォルダを選択",

        // ---- SOQL ----
        ["Soql_Run"] = "▶ 実行 (Ctrl+Enter)",
        ["Soql_PreferRest"] = "REST優先",
        ["Soql_PreferRestTip"] = "REST API（アクセストークン）で実行し、失敗時は sf data query にフォールバック",
        ["Soql_ToolingApi"] = "Tooling API",
        ["Soql_HistoryTip"] = "最近実行した SOQL を読み込み",
        ["Soql_ExportCsv"] = "CSV出力",
        ["Soql_CopyResults"] = "結果をコピー",
        ["Soql_EnterQuery"] = "SOQL を入力してください",
        ["Soql_ResultFmt"] = "{0} / {1} 件 / {2:F0} ms",
        ["Soql_NoResultsToExport"] = "出力できる結果がありません",
        ["Soql_CsvSaveTitle"] = "SOQL 結果を CSV 保存",
        ["Soql_CsvFilter"] = "CSV ファイル (*.csv)|*.csv|すべてのファイル (*.*)|*.*",
        ["Soql_CsvSavedFmt"] = "CSV 出力: {0}",
        ["Soql_CsvFailedFmt"] = "CSV 出力に失敗: {0}",
        ["Soql_NoResultsToCopy"] = "コピーできる結果がありません",
        ["Soql_Copied"] = "結果をクリップボードにコピーしました（TSV）",
        ["Soql_NoQueryFavorite"] = "お気に入りに追加する SOQL がありません",

        // ---- 匿名Apex ----
        ["Apex_Run"] = "▶ 実行 (Ctrl+Enter)",
        ["Apex_LoadFile"] = "読込…",
        ["Apex_SaveFile"] = "保存…",
        ["Apex_HistoryTip"] = "最近実行した匿名Apex を読み込み",
        ["Apex_FetchLatestLog"] = "最新ログを表示",
        ["Apex_FetchLatestLogTip"] = "org に保存されている最新のデバッグログを取得",
        ["Apex_LogsTip"] = "デバッグログ（sf apex run の実行ログ / org から取得したログ）",
        ["Apex_EnterCode"] = "Apex コードを入力してください",
        ["Apex_CompileError"] = "コンパイルエラー",
        ["Apex_CompileErrorFmt"] = "コンパイルエラー: {0}",
        ["Apex_RuntimeException"] = "実行時例外",
        ["Apex_ExceptionFmt"] = "例外 (line {0}, column {1}): {2}{3}",
        ["Apex_SuccessFmt"] = "成功 / {0:F0} ms",
        ["Apex_SuccessWithLogs"] = "実行成功（デバッグログを表示中）",
        ["Apex_Success"] = "実行成功",
        ["Apex_ErrorUnknown"] = "(詳細不明)",
        ["Apex_NoOrgLogs"] = "org に保存されたデバッグログがありません（Setup の Debug Logs / sf apex tail log で作成できます）",
        ["Apex_OpenTitle"] = "匿名Apex ファイルを開く",
        ["Apex_OpenFilter"] = "Apex ファイル (*.apex)|*.apex|テキスト (*.txt)|*.txt|すべてのファイル (*.*)|*.*",
        ["Apex_LoadedFmt"] = "読み込み: {0}",
        ["Apex_LoadFailedFmt"] = "読み込みに失敗: {0}",
        ["Apex_NoCodeToSave"] = "保存するコードがありません",
        ["Apex_SaveTitle"] = "匿名Apex を保存",
        ["Apex_SaveFilter"] = "Apex ファイル (*.apex)|*.apex|すべてのファイル (*.*)|*.*",
        ["Apex_NoCodeFavorite"] = "お気に入りに追加するコードがありません",
        ["Apex_LatestLogFmt"] = "最新ログを取得しました（{0:N0} 文字）",
        ["Apex_LatestLogFailedFmt"] = "ログ取得に失敗: {0}",

        // ---- デバッグログ ----
        ["Log_Refresh"] = "⟳ 一覧更新",
        ["Log_Fetch"] = "取得",
        ["Log_FetchTip"] = "選択したログの内容を表示（ダブルクリックでも可）",
        ["Log_Save"] = "保存…",
        ["Log_Initial"] = "「⟳ 一覧更新」でログ一覧を取得します",
        ["Log_ColStart"] = "開始時刻",
        ["Log_ColOperation"] = "操作",
        ["Log_ColStatus"] = "状態",
        ["Log_ColDuration"] = "時間(ms)",
        ["Log_ColSize"] = "サイズ",
        ["Log_LoadingList"] = "ログ一覧を取得中…",
        ["Log_CountFmt"] = "ログ {0} 件",
        ["Log_ListFailedFmt"] = "ログ一覧の取得に失敗: {0}",
        ["Log_SelectToFetch"] = "取得するログを選択してください",
        ["Log_FetchingFmt"] = "ログ {0} を取得中…",
        ["Log_Unavailable"] = "(内容を取得できませんでした)",
        ["Log_FetchedFmt"] = "取得完了（{0:N0} 文字）",
        ["Log_FetchFailedFmt"] = "ログの取得に失敗: {0}",
        ["Log_NoLogToSave"] = "保存するログがありません",
        ["Log_SaveTitle"] = "デバッグログを保存",
        ["Log_SaveFilter"] = "ログ ファイル (*.log)|*.log|テキスト (*.txt)|*.txt|すべてのファイル (*.*)|*.*",

        // ---- 履歴 ----
        ["History_TypeLabel"] = "種別:",
        ["History_SearchLabel"] = "検索:",
        ["History_SearchTip"] = "概要 / パラメータ / 組織 / フォルダを検索",
        ["History_Refresh"] = "⟳ 更新",
        ["History_CopyParams"] = "パラメータをコピー",
        ["History_CopyParamsTip"] = "選択した履歴の SOQL / Apex / コマンド内容をコピー",
        ["History_DeleteSelected"] = "選択を削除",
        ["History_ClearAll"] = "すべて削除",
        ["History_ColTime"] = "日時",
        ["History_ColType"] = "種別",
        ["History_ColOrg"] = "組織",
        ["History_ColFolder"] = "フォルダ",
        ["History_ColSummary"] = "概要",
        ["History_ColStatus"] = "状態",
        ["History_ColDuration"] = "所要(ms)",
        ["History_Empty"] = "まだ履歴がありません。SOQL / 匿名Apex / コマンドの実行が自動記録されます。",
        ["History_DeleteConfirmFmt"] = "この履歴を削除しますか？{0}{1} [{2}] {3}",
        ["History_ClearConfirm"] = "すべての履歴を削除しますか？（結果ファイルも削除されます）",
        ["Type_Soql"] = "SOQL",
        ["Type_Apex"] = "匿名Apex",
        ["Type_Command"] = "コマンド",
        ["Type_Api"] = "API",
        ["Type_Deploy"] = "デプロイ",
        ["Type_Org"] = "組織",
        ["Status_Success"] = "成功",
        ["Status_Error"] = "失敗",
        ["Status_Canceled"] = "取消",

        // ---- コマンド ----
        ["Command_Run"] = "▶ 実行 (Enter)",
        ["Command_InputTip"] = "sf に渡す引数（例: org list / data query --query SELECT Id FROM Account LIMIT 5）。sf 付きの貼り付けも可",
        ["Command_StdOutTab"] = "標準出力",
        ["Command_StdErrTab"] = "標準エラー",
        ["Command_Enter"] = "コマンドを入力してください",
        ["Command_EnterArgs"] = "sf の引数を入力してください（例: org list）",
        ["Command_HistoryTip"] = "最近実行したコマンドを読み込み",
        ["Command_DangerConfirmFmt"] = "「{0}」を含む操作です。実行しますか？{1}{1}sf {2}",
        ["Command_NoCommandFavorite"] = "お気に入りに追加するコマンドがありません",

        // ---- REST API ----
        ["Api_Send"] = "送信",
        ["Api_PathTip"] = "instanceUrl からのパス（例: /services/data/v67.0/limits / /services/data/v67.0/sobjects）",
        ["Api_HistoryTip"] = "最近送信したリクエストを読み込み",
        ["Api_BodyLabel"] = "リクエスト ボディ（JSON・POST/PATCH で使用）",
        ["Api_ResponseTip"] = "レスポンス（JSON は整形して表示）",
        ["Api_EnterPath"] = "パスを入力してください（例: /services/data/v67.0/limits）",
        ["Api_SendConfirmFmt"] = "{0} リクエストを送信します。実行しますか？{1}{1}{0} {2}",
        ["Api_Sending"] = "送信中…",
        ["Api_NoPathFavorite"] = "お気に入りに追加するパスがありません",

        // ---- デプロイ ----
        ["Deploy_Operation"] = "操作:",
        ["Deploy_SourcePath"] = "ソースパス:",
        ["Deploy_SourceTip"] = "デプロイするソース（例: force-app）。空欄なら変更分をデプロイ（tracked changes）",
        ["Deploy_Manifest"] = "マニフェスト:",
        ["Deploy_ManifestTip"] = "package.xml のパス（省略可）",
        ["Deploy_TestLevel"] = "テストレベル:",
        ["Deploy_Tests"] = "指定テスト:",
        ["Deploy_TestsTip"] = "RunSpecifiedTests のときの Apex テスト名（カンマ区切り）",
        ["Deploy_JobIdTip"] = "レポート / クイックデプロイ用のジョブ ID（空欄なら --use-most-recent）",
        ["Deploy_UseMostRecent"] = "最新を使用",
        ["Deploy_UseMostRecentTip"] = "--use-most-recent（直近の検証/デプロイを使用）",
        ["Deploy_HistoryTip"] = "最近のデプロイ操作を読み込み",
        ["Deploy_PreviewTip"] = "実行されるコマンド（コピー可）",
        ["Deploy_OutputTip"] = "sf の出力（JSON は整形して表示）",
        ["Deploy_ConfirmFmt"] = "デプロイ操作を実行します。よろしいですか？{0}{0}{1}",
        ["Deploy_Running"] = "実行中…（完了まで出力は表示されません。「キャンセル」で中断できます）",
        ["Deploy_ExitFmt"] = "終了コード: {0} / {1:F1} 分",
        ["Deploy_BrowseSourceTitle"] = "ソースディレクトリを選択",
        ["Deploy_BrowseManifestTitle"] = "package.xml（マニフェスト）を選択",
        ["Deploy_ManifestFilter"] = "マニフェスト (*.xml)|*.xml|すべてのファイル (*.*)|*.*",
        ["Op_Deploy"] = "デプロイ (start)",
        ["Op_Validate"] = "検証 (validate)",
        ["Op_Quick"] = "クイックデプロイ (quick)",
        ["Op_Report"] = "レポート (report)",
        ["Op_Retrieve"] = "メタデータ取得 (retrieve)",

        // ---- クイックパネル ----
        ["Quick_Title"] = "クイックパネル（Ctrl+1..9）",
        ["Quick_TitleTip"] = "お気に入りを登録した順に表示。Ctrl+数字で即実行できます",
        ["Quick_Hint"] = "ダブルクリック / Ctrl+数字 で実行、右クリックで削除",
        ["Quick_Run"] = "実行",
        ["Quick_Remove"] = "お気に入りから削除",
        ["Quick_ConfirmRemoveFmt"] = "お気に入りから削除しますか？{0}[{1}] {2}",
        ["Quick_TypeUrl"] = "URL",
        ["Quick_TypeFolder"] = "フォルダ",

        // ---- 設定 ----
        ["Settings_Title"] = "設定",
        ["Settings_DataRootFmt"] = "データフォルダ: {0}",
        ["Settings_OpenDataFolder"] = "データフォルダを開く",
        ["Settings_Reload"] = "再読込",
        ["Settings_ReloadTip"] = "ファイルの現在値でフォームを初期化",
        ["Settings_SfGroup"] = "Salesforce CLI",
        ["Settings_SfPath"] = "sf パス:",
        ["Settings_SfPathTip"] = "sf.cmd のフルパス。空欄なら自動検出（環境変数 SFUI_SF_PATH → Program Files → PATH）",
        ["Settings_Browse"] = "参照…",
        ["Settings_Clear"] = "クリア",
        ["Settings_ClearTip"] = "空欄に戻して自動検出を使用",
        ["Settings_ToolsGroup"] = "ツール",
        ["Settings_Terminal"] = "ターミナル:",
        ["Settings_TerminalTip"] = "Windows Terminal (wt.exe) のフルパス。空欄なら自動検出",
        ["Settings_VsCode"] = "VS Code:",
        ["Settings_VsCodeTip"] = "code.cmd のフルパス。空欄なら自動検出",
        ["Settings_HistoryGroup"] = "履歴と結果",
        ["Settings_HistoryLimit"] = "履歴の上限:",
        ["Settings_PerType"] = "件 / 種別",
        ["Settings_Threshold"] = "結果保存閾値:",
        ["Settings_ThresholdSuffix"] = "KB を超えた結果は results/ に分離保存",
        ["Settings_SeedSamples"] = "サンプル履歴を投入（SOQL / 匿名Apex / コマンド / REST）",
        ["Settings_SeedSamplesTip"] = "よく使うテンプレートを履歴に追加します（同じ内容はスキップ）",
        ["Settings_ConfirmGroup"] = "実行前確認",
        ["Settings_ConfirmPolicy"] = "確認ポリシー:",
        ["Settings_Save"] = "保存",
        ["Settings_Loaded"] = "現在の設定を読み込みました",
        ["Settings_DetectedFmt"] = "自動検出: sf={0} / wt={1} / code={2}",
        ["Settings_BrowseSfTitle"] = "sf 実行ファイルを選択（sf.cmd）",
        ["Settings_SfFilter"] = "sf コマンド (*.cmd;*.exe;*.bat)|*.cmd;*.exe;*.bat|すべてのファイル (*.*)|*.*",
        ["Settings_BrowseTerminalTitle"] = "Windows Terminal (wt.exe) を選択",
        ["Settings_ExeFilter"] = "実行ファイル (*.exe)|*.exe|すべてのファイル (*.*)|*.*",
        ["Settings_BrowseVsCodeTitle"] = "VS Code CLI (code.cmd) を選択",
        ["Settings_CodeFilter"] = "code (*.cmd;*.exe;*.bat)|*.cmd;*.exe;*.bat|すべてのファイル (*.*)|*.*",
        ["Settings_SeedConfirmFmt"] = "代表的なサンプル（SOQL / 匿名Apex / コマンド / REST API）を履歴に追加しますか？{0}同じ内容が既にある場合はスキップされます。",
        ["Settings_SeedDoneFmt"] = "サンプル履歴: 追加 {0} 件 / スキップ {1} 件",
        ["Settings_InvalidHistoryLimit"] = "履歴上限は 1 以上の整数で入力してください",
        ["Settings_InvalidThreshold"] = "結果保存閾値は 0 以上の整数（KB）で入力してください",
        ["Settings_SavedSfMissing"] = "保存しました（sf が見つかりません。パスを確認してください）",
        ["Settings_SavedSfFmt"] = "保存しました / sf: {0}",
        ["Policy_Dangerous"] = "危険操作のみ確認",
        ["Policy_Always"] = "常に確認",
        ["Policy_Never"] = "確認しない",

        // ---- Core（エラーメッセージ等）----
        ["Core_OrgSelectRequired"] = "対象組織が指定されていません。",
        ["Core_SoqlRequired"] = "SOQL が入力されていません。",
        ["Core_OrgListFailedFmt"] = "組織一覧の取得に失敗しました: {0}",
        ["Core_TokenFailedFmt"] = "アクセストークンの取得に失敗しました ({0}): {1}",
        ["Core_ApexRunFailed"] = "実行に失敗しました。",
        ["Core_LogListFailedFmt"] = "ログ一覧の取得に失敗しました: {0}",
        ["Core_LogFetchFailedFmt"] = "ログの取得に失敗しました: {0}",
        ["Core_InstanceUrlMissing"] = "組織の instanceUrl を取得できませんでした。",
        ["Core_SfNotFound"] = "sf コマンドが見つかりません。Salesforce CLI をインストールするか、環境変数 SFUI_SF_PATH で sf.cmd の場所を指定してください。",
        ["Core_SfStartFailedFmt"] = "sf コマンドの起動に失敗しました: {0}",
        ["Core_Timeout"] = "コマンドがタイムアウトしました。",
        ["Core_FailedExitCodeFmt"] = "コマンドが失敗しました (ExitCode={0})。",
        ["Core_SoqlFailedFmt"] = "SOQL 実行に失敗しました: {0}",
        ["Launch_PsFmt"] = "PowerShell を起動: {0}",
        ["Launch_CmdFmt"] = "コマンド プロンプトを起動: {0}",
        ["Launch_WslFmt"] = "WSL を起動: {0}",
        ["Launch_WtFmt"] = "Windows Terminal を起動: {0}",
        ["Launch_CmdFallbackFmt"] = "コマンド プロンプトを起動（Windows Terminal 未検出）: {0}",
        ["Launch_TerminalFailedFmt"] = "ターミナルの起動に失敗: {0}",
        ["Launch_ExplorerFmt"] = "エクスプローラー: {0}",
        ["Launch_ExplorerFailedFmt"] = "エクスプローラーの起動に失敗: {0}",
        ["Launch_VsCodeNotFound"] = "VS Code (code.cmd) が見つかりません。",
        ["Launch_VsCodeFmt"] = "VS Code を起動: {0}",
        ["Launch_VsCodeFailedFmt"] = "VS Code の起動に失敗: {0}",
        ["Launch_BrowserFmt"] = "ブラウザ: {0}",
        ["Launch_BrowserFailedFmt"] = "ブラウザの起動に失敗: {0}",

        // ---- サンプル履歴（要約）----
        ["Sample_Soql_Basic"] = "取引先の基本一覧（10 件）",
        ["Sample_Soql_Industry"] = "取引先（業種・売上つき、更新が新しい順 20 件）",
        ["Sample_Soql_Count"] = "取引先の件数",
        ["Sample_Soql_Recent"] = "直近 7 日で作成された取引先",
        ["Sample_Soql_Contacts"] = "担当者（メールつき、更新が新しい順 20 件）",
        ["Sample_Soql_Rel"] = "担当者と取引先名（リレーション）",
        ["Sample_Soql_Opps"] = "進行中の商談（クローズ日順 50 件）",
        ["Sample_Soql_Tasks"] = "未完了の ToDo（期日順 50 件）",
        ["Sample_Soql_Users"] = "アクティブユーザー（50 件）",
        ["Sample_Apex_UserInfo"] = "ユーザーと組織の情報を表示",
        ["Sample_Apex_Query"] = "取引先を 5 件取得してログ出力",
        ["Sample_Apex_Savepoint"] = "セーブポイントでロールバック（安全な DML サンプル）",
        ["Sample_Apex_Limits"] = "ガバナ制限（Limits）の確認",
        ["Sample_Apex_DmlCatch"] = "DmlException のハンドリング例",
        ["Sample_Apex_Json"] = "Map の JSON シリアライズ例",
        ["Sample_Command_OrgList"] = "認証済み組織の一覧",
        ["Sample_Command_OrgDisplay"] = "選択中の組織の情報（URL / API バージョン等）",
        ["Sample_Command_OrgOpen"] = "組織のホームをブラウザで開く",
        ["Sample_Command_DataQuery"] = "CLI 経由の SOQL（REST のフォールバック確認用）",
        ["Sample_Command_LogList"] = "デバッグログの一覧（直近分）",
        ["Sample_Command_LogGet"] = "最新のデバッグログを取得",
        ["Sample_Command_DeployReport"] = "直前のデプロイ結果を確認",
        ["Sample_Command_AliasList"] = "エイリアス（組織の別名）一覧",
        ["Sample_Api_Limits"] = "API 利用状況（制限値と現在の消費量）",
        ["Sample_Api_Sobjects"] = "オブジェクト一覧（メタデータ）",
        ["Sample_Api_Describe"] = "取引先（Account）の項目定義",
        ["Sample_Api_Query"] = "REST 経由の SOQL（アカウント 5 件）",
        ["Sample_Api_Tooling"] = "Tooling API: Apex クラス一覧（10 件）",
        ["Sample_Api_Recent"] = "最近参照したレコード",
        ["Sample_Api_Count"] = "取引先の件数（COUNT クエリ）",
    };
}
