<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SfUi</AssemblyName>
    <RootNamespace>SfUi.App</RootNamespace>
    <Version>0.11.0</Version>
    <ApplicationIcon>SfUi.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="SfUi.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SfUi.Core\SfUi.Core.csproj" />
    <ProjectReference Include="..\SfUi.Presentation\SfUi.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
  </ItemGroup>

</Project>
